parameters:

services:
  Symfony\Component\Serializer\Encoder\XmlEncoder: ~
  Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor: ~
  Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter: ~
  Symfony\Component\Serializer\Normalizer\DateTimeNormalizer: ~
  Symfony\Component\Serializer\Normalizer\ArrayDenormalizer: ~
  Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    arguments:
      $nameConverter: '@Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter'
      $propertyTypeExtractor: '@Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor'

  # Define the Serializer service with arguments
  Symfony\Component\Serializer\Serializer:
    arguments:
      - [
          '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer',
          '@Symfony\Component\Serializer\Normalizer\DateTimeNormalizer',
          '@Symfony\Component\Serializer\Normalizer\ArrayDenormalizer',
      ]
      - [ '@Symfony\Component\Serializer\Encoder\XmlEncoder' ]

  # Optional: create an alias for convenience
  xml_serializer: '@Symfony\Component\Serializer\Serializer'
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\CurrencyRateProvider\CBRProvider:
    arguments:
      $url: '%env(CBR_API_URL)%'
      $serializer: '@xml_serializer'
  App\CurrencyRateProvider\ECBProvider:
    arguments:
      $url: '%env(ECB_API_URL)%'
      $serializer: '@xml_serializer'

  _instanceof:
    App\CurrencyRateProvider\CurrencyRateProviderInterface:
      tags: [ 'currency_rate_provider' ]

    App\Service\UpdateRates:
      calls:
        - method: updateRates
          arguments:
            - '@App\CurrencyRateProvider\CBRProvider'
            - '@App\CurrencyRateProvider\ECBProvider'
